### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by bay-jacewhitten** [growthbook/devtools#3]
When using the devtool extension I get this error in my browser console. Goes away when disabled.

`Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.`

![Screen Shot 2022-09-30 at 9 51 25 AM](https://user-images.githubusercontent.com/79159096/193319104-5d5687e8-1a9d-4af6-a140-3a598d7f6069.png)

**Comment by shakazullu94** [comment]
@bay-jacewhitten have you managed to solve this?

**Comment by bay-jacewhitten** [comment]
I know longer use the extension. I was not able to successfully quiet this
error.

**Comment by RiZKiT** [comment]
This is still an issue and quite annoying. It takes about 4 seconds after loading of the page to appear. It's definitely related to this extension, because it does not appear when extension is disabled.

**Comment by bttf** [comment]
I believe this has been fixed - please update to version 0.3.2 of the chrome extension if you haven't already.
